### ISSUE TITLE
Cannot install captainhook/plugin-composer

### ISSUE THREAD

**Issue by shochdoerfer** [captainhook-git/plugin-composer#2]
When running `composer require --dev captainhook/plugin-composer` I get the following output:
```
Using version ^5.0 for captainhook/plugin-composer
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing captainhook/plugin-composer (5.0.0): Loading from cache
Writing lock file
Generating autoload files
CaptainHook Composer Plugin
```

Nothing happens after that. Composer seems to be stuck at some point. At first, I thought it's an issue since I ran the command in Docker but I get the same result when running the command on the host. Passing the verbose flag to Composer does not show any more output.

My PHP version is `PHP 7.2.27-1+ubuntu18.04.1+deb.sury.org+1`

**Comment by shochdoerfer** [comment]
Installing version 4.x and upgrading to version 5.x seems to work though.

**Comment by sebastianfeldmann** [comment]
Yes version 5 of the composer plugin does not require the CaptainHook base package anymore, because you can use the composer plugin with the PHAR file as well and then you do not need the base package :/ (not ideal)

I would argue that the composer plugin should be replaced by a script line in your local `composer.json`

```
"script": {
  "post-install": "vendor/bin/captainhook install -f --skip-existing"
}
```

**Comment by heiglandreas** [comment]
I'd rather argue that the plugin always installs the base package. And if you use the PHAR you'd add the post-install script to your composer.json.

The reasoning is that if you use the PHAR, you most probably want to keep your dev-requirements as clean as possible, so you'd not want the plugin in there as well and if you install the plugin you are fine with added stuff in your dev-requirements....

**Comment by sebastianfeldmann** [comment]
You are right. Supporting every option everywhere doesn’t make sense in that case.

I will change the docs and the `plugin-composer` package so the base Package will be installed again

**Comment by shochdoerfer** [comment]
My bad, I had installed the CaptainHook base before that and tried to install the Composer plugin afterwards. The "install 4.x and upgrade to 5.x" method worked fine locally but did not succeed within Docker. Maybe something is completely off. Will do some more tests and let you know about my findings.

**Comment by heiglandreas** [comment]
It should be sufficient to *only* require the plugin (after it is fixed). When you do a `composer require --dev captainhook/plugin-composer` it will also install captainhook. So there is no need to install "The Captain" separately which then might avoid confusions ;-)

**Comment by shochdoerfer** [comment]
Which still does not explain why the Composer require process "hang".

**Comment by sebastianfeldmann** [comment]
Maybe it does, somehow :/

The update removed the `CaptainHook`  base package because version 5 does not require it anymore.
The composer plugin was still loaded in the same process, so the v4 plugin wanted to install the hooks. After removing the base package, the files the v4 plugin required to execute where gone.
And the v5 plugin couldn't find those files either because it did not require the previously removed base package.

Either way I would expect it to crash instead of just hanging :)

Oh man removing the dependency was a master fail :/

**Comment by shochdoerfer** [comment]
Initially, I installed base v5 first, that looked good and tried to install the composer plugin v5 afterwards. So I would have expected that everything runs smoothly but it did not.

I wish I could say I will stop using this project, but I guess I am way too involved in this to opt out :P

**Comment by sebastianfeldmann** [comment]
I've re-added the `captainhook/captainhook` package to the dependency list.

This should make the usage of the plugin much more convenient.
