### ISSUE TITLE
Option to skip installing hooks if config file does not exist

### ISSUE THREAD

**Issue by emodric** [captainhook-git/plugin-composer#9]
Hi!

Would you be willing to have an option in the plugin to skip installing hooks if the config file does not exist, rather than creating a default config file? The option could be enabled through using `$extra['captainhook']` config in `composer.json`.

If so, I can work on a PR.

**Comment by heiglandreas** [comment]
I wonder what would be the use case for that?

If you want to install The Capt'n why would you not want to use it?

**Comment by emodric** [comment]
It's an open source Symfony and eZ based template site, for which we use Captain Hook for our client project development based on the site, but I would not want to force it for other users (i.e. open source community).

I would like to have installed by default, however, to reduce steps needed for us to get the new project running.

**Comment by sebastianfeldmann** [comment]
Couldn't you include an empty `captainhook.json` or a default one where all hooks are disabled?

**Comment by heiglandreas** [comment]
Well.... The idea is actually check in the `captainhook.json` so that everyone uses the same hooks....

If you do not want to enforce the use of the hooks in general then perhaps using CaptainHook isn't the right thing...

Or what does @sebastianfeldmann think?

**Comment by emodric** [comment]
> Couldn't you include an empty captainhook.json or a default one where all hooks are disabled?

We already do. And to solve our usecase we basically run `bin/captainhook install --force` and install empty hooks on every composer install, and in case of our client projects, we replace `captainhook.json` with ours.

It works well, however, I was thinking the intention could be clearer if we don't even run captain hook if config does not exist.

Either way, if you think that the feature does not make sense, we have a working solution, so no big deal.

**Comment by sebastianfeldmann** [comment]
I'm trying to come up with a use case where it could be useful as well, but I think this is just a very special use case you have there.

**Comment by emodric** [comment]
Probably, yes :+1:

**Comment by heiglandreas** [comment]
Could perhaps a `captainhook.override.json` solve the issue?

So that you can overwrite the checked in file with a local one....

**Comment by emodric** [comment]
Hm, not exactly the usecase, as we don't have a local/not commited `captainhook.json`.

Anyway, I agree with @sebastianfeldmann that our usecase is overly specific :)

**Comment by sebastianfeldmann** [comment]
I think @emodric is working on a template project that people could use to create new projects fast.

If he and his colleagues use the template to create a new project he is fine with setting up the Cap'n but since the template project is open source he does not want to force everyone, who uses the template project to setup a new project, to setup and use the Cap'n as well.

In this very special use case it would make sense to install the dependency but not running the setup/install routine.

I would argue, that removing the dependency in the first place and only install it for your "personal" projects would be the "cleaner" solution.

As sad as I am seeing you remove the "hard" dependency to the Cap'n (I love when people use the Cap'n) I think adding the dependency manually after creating the new project with your template project is the "better" solution for the open source variant, obviously not for your own project since you would have to set the Cap'n up manually for every new project.

**Comment by emodric** [comment]
@sebastianfeldmann got it right. The usecase is exactly that :)

> I would argue, that removing the dependency in the first place and only install it for your "personal" projects would be the cleaner solution.

Maybe. In our case, additional `composer install` is somewhat more complicated than just having an additional file and symlinking it by running a command which we already run for project initialization (preparing various config files). Having said that, I agree that there is no need for any changes here, so I'll close this :)
